### PR TITLE
Update index.adoc

### PR DESCRIPTION
**Pull request by terrylblessing**
For clause needs a comma. Doing this PR so I can sign another CLA on this new github account for MuleSoft.

### CODE REVIEW

**Comment by terrylblessing** [comment]
When I click the link, I get "You already signed the CLA on 2022-03-18". Not sure what the issue is.

Oops, an error occurred
This exception has been logged with id 7n3fj2gjh.


cc: @valkyrie69

**Review by sathya0 — APPROVED** [review]

**Comment by sathya0** [comment]
You're good to go, @terrylblessing! Thanks for your contribution. Feel free to merge this PR.

**Comment by terrylblessing** [comment]
> You're good to go, @terrylblessing! Thanks for your contribution. Feel free to merge this PR.

Thanks @sathya0 but I don't have write access to the repo yet.

`Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.`

There is no merge button available for me. cc: @valkyrie69

**Comment by sathya0** [comment]
Gotcha @terrylblessing, you may have to request access to the MuleSoft org on GitHub (which you might have already done). Here are some instructions if you haven't already checked them out:
https://concierge.it.salesforce.com/articles/en_US/Supportforce_Article/MuleSoft-Github-Repos-Orgs-Request-Access

**Comment by terrylblessing** [comment]
> Gotcha @terrylblessing, you may have to request access to the MuleSoft org on GitHub (which you might have already done). Here are some instructions if you haven't already checked them out: https://concierge.it.salesforce.com/articles/en_US/Supportforce_Article/MuleSoft-Github-Repos-Orgs-Request-Access

Thanks @sathya0 I had logged a ticket but it seems to be stagnating. I just logged another one. cc: @valkyrie69

**Comment by sathya0** [comment]
Great, they might take a couple of days but it looks like everything is good from your side now. Thanks for getting on that quick! 😄 @terrylblessing

**Comment by terrylblessing** [comment]
> Great, they might take a couple of days but it looks like everything is good from your side now. Thanks for getting on that quick! 😄 @terrylblessing

Well I know I need to review some PRs early next week so the sooner the better!

**Comment by terrylblessing** [comment]
@valkyrie69 can someone please merge this PR for me or give me access to the repo?

**Comment by terrylblessing** [comment]
@sathya0 could you please merge this PR for me? I don't have write access to the repo.

**Pull request merged**
