### PR TITLE
Update scripting-module-studio.adoc

### PR DESCRIPTION
**Pull request by Jani-product**
# Writer's Quality Checklist

Before merging your PR, did you:

- [x] Run spell checker
- [x] Run link checker to check for broken xrefs
- [x] Check for orphan files
- [x] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [x] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [x] If applicable, verify that the software actually got released

### CODE REVIEW

**Comment by Jani-product** [comment]
Just a minor change it should be Mulesoft Anypoint studio instead of mulesoft pattern

**Comment by Jani-product** [comment]
Updated the CLA but it's still showing CLA needs to be updated !

**Comment by Jani-product** [comment]
> .

I've already signed why is it showing error

**Comment by kevintroller** [comment]
Closing this PR, as the change was merged under https://github.com/mulesoft/docs-connectors/pull/2151

**Pull request closed without merging**
