### PR TITLE
Add link to newest version

### PR DESCRIPTION
**Pull request by ca-stefan-cordes**
Link from external to jump to newest version. https://docs.mulesoft.com/sap-connector/

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

### CODE REVIEW

**Comment by sathya0** [comment]
Hey @ca-stefan-cordes, could you give some context for this change please? Thanks!

**Comment by ca-stefan-cordes** [comment]
We have a page on our intranet which say:
The SAP Connector Documentation you can find <here>.
<here> == https://docs.mulesoft.com/sap-connector/5.8

And Link needs to be amended each time a new version of a connector is released.
This applies to all connectors.

https://docs.mulesoft.com/sap-connector/latest
seems not to work.

**Comment by sathya0** [comment]
@ca-stefan-cordes If you use this link, the page automatically points to the latest version of SAP Connector: https://docs.mulesoft.com/connectors/sap/sap-connector. We don't use "latest" for connectors. Which page contains the link to SAP MuleSoft docs?

**Comment by ca-stefan-cordes** [comment]
Great thanks, https://docs.mulesoft.com/connectors/sap/sap-connector works.
(Does this work with all connectors ?)

(containing page is our private wiki)

**Comment by sathya0** [comment]
@ca-stefan-cordes It works with most connectors, it doesn't work for the newer connectors unfortunately

**Pull request closed without merging**
