### PR TITLE
Update amazon-sqs-connector.adoc

### PR DESCRIPTION
**Pull request by janbily**

### CODE REVIEW

**Comment by mauro-dentoni** [comment]
@dhirsch1 @george-hoffer can you please help us reviewing this docs? Thanks in advance!

**Comment by mauro-dentoni** [comment]
@mulesoft/team-docs, please, notice this version was released yesterday. Please, check the related channel. Thanks!!

**Comment by dhirsch1** [comment]
Thanks for the edit. These files were not in a PR and are not ready to be merged so I am going to close this PR once I capture your edits/suggestions.

**Comment by george-hoffer** [comment]
Replaced by https://github.com/mulesoft/docs-connectors/pull/379

**Pull request closed without merging**
